objects/Class_SFDC_Session__c.object
<CustomObject>
    <description>A specific class session that is held with attendance documented</description>
    <fields>
        <fullName>Class__c</fullName>
        <description>Class for this session</description>
        <inlineHelpText>Enter the class for this session</inlineHelpText>
        <label>Class</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Class must be active and begin date is after today</errorMessage>
            <filterItems>
                <field>SFDC_Class__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Class must be active and begin date is after today</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SFDC_Class__c</referenceTo>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <defaultValue>Now()</defaultValue>
        <description>Date / Time the Class session starts</description>
        <inlineHelpText>Enter the Date and time the class session starts</inlineHelpText>
        <label>Start Date Time</label>
        <type>DateTime</type>
    </fields>
    <label>Class Session</label>
    <nameField>
        <displayFormat>SESSION-{00000}</displayFormat>
        <label>Class Session ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Class_SFDC_Session_Attendance__c.object
<CustomObject>
    <description>Individual student attendance record for a session</description>
    <label>Class Session Attendance</label>
    <nameField>
        <displayFormat>ATTEND-{00000}</displayFormat>
        <label>Class Session Attendance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Session Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>ClassroomStudent</fullName>
        <active>true</active>
        <description>Class Student</description>
        <label>ClassroomStudent</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SFDC_Class__c.object
<CustomObject>
    <description>Track the date and location of where your various Courses will be taught, and who has enrolled in this Class.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is the class active and open for enrollment or shown</description>
        <inlineHelpText>Is this class active and open for enrollment?</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instructor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Instructor not known</errorMessage>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>ClassroomStaff</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>R00N40000001QAyhEAG</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SFDC_Enrollment__c.object
<CustomObject>
    <description>Connector object that associates a Student to a Class.</description>
    <fields>
        <fullName>Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Class</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SFDC_Class__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SFDC_Class__c</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>R00N40000001QAyfEAG</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Student Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>ClassroomStudent</value>
            </filterItems>
            <filterItems>
                <field>Contact.Active_Student__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>R00N40000001QAygEAG</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Registered</fullName>
                    <default>true</default>
                    <label>Registered</label>
                </value>
                <value>
                    <fullName>Wait Listed</fullName>
                </value>
                <value>
                    <fullName>Enrolled</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000}</displayFormat>
        <label>Enrollment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CLASS_SFDC_SessionTriggerHandler_Test.cls
@isTest
public class CLASS_SFDC_SessionTriggerHandler_Test {
    
    public static testMethod void testCreateSessionTrigger() {
       //create test data
       RecordType rt = [SELECT id,DeveloperName FROM RecordType WHERE DeveloperName = 'ClassroomStudent'];
       Contact student1 = new Contact(lastname='laststudent1', recordtypeid=rt.id);
       insert student1;
        Contact student2 = new Contact(lastname='laststudent2',recordtypeid=rt.id);
       insert student2;
       SFDC_Class__c newClass = new SFDC_Class__c(Active__c=true, Name='Class1'); 
       insert newClass;
       student1 = [select id from contact limit 1];
       student2 = [select id from contact limit 1];
       newClass = [select id from SFDC_Class__c limit 1];
       sfdc_enrollment__c enroll1 = new sfdc_enrollment__c(class__c = newClass.Id, status__c='Registered', 
                                                          contact__c=student1.id);
       sfdc_enrollment__c enroll2 = new sfdc_enrollment__c(class__c = newClass.Id, status__c='Registered', 
                                                          contact__c=student2.id);
       insert enroll1;insert enroll2;
       Class_SFDC_Session__c aSession = new Class_SFDC_Session__c (Class__c = newClass.Id, Start_Date_Time__C = DateTime.now());
       insert aSession;
       System.assert([select count() from Class_SFDC_Session_Attendance__c] == 2);
        
    }
        

}