objects/Class_SFDC_Session__c.object
<CustomObject>
    <description>A specific class session that is held with attendance documented</description>
    <fields>
        <fullName>Class__c</fullName>
        <description>Class for this session</description>
        <inlineHelpText>Enter the class for this session</inlineHelpText>
        <label>Class</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Class must be active and begin date is after today</errorMessage>
            <filterItems>
                <field>SFDC_Class__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Class must be active and begin date is after today</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SFDC_Class__c</referenceTo>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <defaultValue>Now()</defaultValue>
        <description>Date / Time the Class session starts</description>
        <inlineHelpText>Enter the Date and time the class session starts</inlineHelpText>
        <label>Start Date Time</label>
        <type>DateTime</type>
    </fields>
    <label>Class Session</label>
    <nameField>
        <displayFormat>SESSION-{00000}</displayFormat>
        <label>Class Session ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Class_SFDC_Session_Attendance__c.object
<CustomObject>
    <description>Individual student attendance record for a session</description>
    <fields>
        <fullName>Attended__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Mark student attendance</description>
        <inlineHelpText>Mark student attended</inlineHelpText>
        <label>Attended</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Class_Session__c</fullName>
        <description>Session for which attendance of student is tracked</description>
        <label>Class Session</label>
        <referenceTo>Class_SFDC_Session__c</referenceTo>
        <relationshipLabel>Class Session Attendances</relationshipLabel>
        <relationshipName>Class_Session_Attendances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student_Friendly_Name__c</fullName>
        <formula>Student_Name__r.FirstName + &apos; &apos; +  Student_Name__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Student_Friendly_Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Name of the student for this attendance record</description>
        <inlineHelpText>Enter name of the student / contact</inlineHelpText>
        <label>Student Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>ClassroomStudent</value>
            </filterItems>
            <filterItems>
                <field>Contact.Active_Student__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Class Session Attendances</relationshipLabel>
        <relationshipName>Class_Session_Attendances</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Class Session Attendance</label>
    <nameField>
        <displayFormat>ATTEND-{00000}</displayFormat>
        <label>Class Session Attendance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Session Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SFDC_Class__c.object
<CustomObject>
    <description>Track the date and location of where your various Courses will be taught, and who has enrolled in this Class.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Instructor</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Instructor not known</errorMessage>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>ClassroomStaff</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Classes</relationshipLabel>
        <relationshipName>R00N40000001QAyhEAG</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <description>For a class that has multiple sections</description>
        <label>Section</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                    <default>true</default>
                    <label>A</label>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>D</fullName>
                </value>
                <value>
                    <fullName>E</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CLASS_SFDC_MarkAttendanceController.cls
// Controller used by the CLASS_SFDC_MarkAttendance visualforce page to constructo the data in the initial page
// as well as saving the attendance changes from the form
public with sharing class CLASS_SFDC_MarkAttendanceController  {

    private final SFDC_Class__c currClass;
    private final Class_SFDC_Session__c currClassSession;
    private final List<Class_SFDC_Session_Attendance__c> currAttendanceList;
    private String QS_id;
    private boolean success=false;


    // constructor
    public CLASS_SFDC_MarkAttendanceController() {
        // Get the class session from the id from the querystring
            QS_id = ApexPages.currentPage().getParameters().get('id');
            // see if qs param is a class session id - coming from session page
            if ([Select id FROM Class_SFDC_Session__c 
                 WHERE Name = :QS_id].size() > 0) {
            	currClassSession = [SELECT Id, Name, Class__c, Start_Date_Time__c FROM Class_SFDC_Session__c
                                WHERE Name = :QS_id limit 1];
                // Get the Class of the class session
            	currClass = [SELECT Id, Name, Section__c, Contact__c, Contact__r.Name FROM SFDC_Class__c
                                WHERE Id = :currClassSession.Class__c limit 1];
             
                     // Get the list of students/contacts that are registered, enrolled, and waitlisted.  Initial list
        			// was created from post insert trigger of the class session
       				 // Pull that list and add any additional students that were added after the initial 
        			// creation of the attendance list
       			currAttendanceList = [SELECT Id, Name, Class_Session__c, Student_Name__c, Student_Name__r.Name, 
                                        Student_Friendly_Name__c, attended__c
                             FROM Class_SFDC_Session_Attendance__c
                             WHERE Class_Session__c = :currClassSession.Id];
       		
             }
            // see if the id is a class id, then coming from the class page.  create new session to mark attendance
             else if ([Select id FROM SFDC_Class__c 
                 WHERE Name = :QS_id].size() > 0) {
                // Get the Class from id sent in from qs (from class page)
            	currClass = [SELECT Id, Name, Section__c, Contact__c, Contact__r.Name FROM SFDC_Class__c
                                WHERE Name = :QS_id limit 1];
                // get the latest created class session - sessions are created every day by batch job for the days
                // that are marked in the class object
                currClassSession = [SELECT Id, Name, Class__c, Start_Date_Time__c, CreatedDate FROM Class_SFDC_Session__c
                                WHERE Class__c = :currClass.Id and CreatedDate = Today
                                ORDER BY Start_Date_Time__c DESC nulls last limit 1];
               // Get the list of students/contacts that are registered, enrolled, and waitlisted.  Initial list
        			// was created from post insert trigger of the class session
       				 // Pull that list and add any additional students that were added after the initial 
        			// creation of the attendance list
       			currAttendanceList = [SELECT Id, Name, Class_Session__c, Student_Name__c, Student_Name__r.Name, 
                                        Student_Friendly_Name__c, attended__c
                             FROM Class_SFDC_Session_Attendance__c
                             WHERE Class_Session__c = :currClassSession.Id];      
        	}
        else {
            ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM,'No Sessions have been created for this class, please create a session for this class'));
            success=false;
            //exit;
        }
           


        //success=true;
 
    }
	
    // getter for class of the session
    public SFDC_Class__c  getCurrClass() {
        return currClass;
    }
	
    // getter for the current session marked for attendance
    public Class_SFDC_Session__c   getCurrClassSession() {
        return currClassSession;
    }

    // getter for list of students being marked for attendance
    public List<Class_SFDC_Session_Attendance__c>   getCurrAttendanceList() {
        return currAttendanceList;
    }    
    
        // getter for success failure of controller
    public boolean  success() {
        return success;
    } 
     // getter for querystring param
    public String   getQS_ID() {
        return QS_id;
    } 
    // save the attendance list from changes in the visual force page    
    public PageReference save() {
        update currAttendanceList;
        success=true;
        ApexPages.AddMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM,'Saved Successfully'));
        return null;
    }
    
}