objects/Class_SFDC_Session__c.object
<CustomObject>
    <description>A specific class session that is held with attendance documented</description>
    <fields>
        <fullName>Class__c</fullName>
        <description>Class for this session</description>
        <inlineHelpText>Enter the class for this session</inlineHelpText>
        <label>Class</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Class must be active and begin date is after today</errorMessage>
            <filterItems>
                <field>SFDC_Class__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Class must be active and begin date is after today</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SFDC_Class__c</referenceTo>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <defaultValue>Now()</defaultValue>
        <description>Date / Time the Class session starts</description>
        <inlineHelpText>Enter the Date and time the class session starts</inlineHelpText>
        <label>Start Date Time</label>
        <type>DateTime</type>
    </fields>
    <label>Class Session</label>
    <nameField>
        <displayFormat>SESSION-{00000}</displayFormat>
        <label>Class Session ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Class_SFDC_Session_Attendance__c.object
<CustomObject>
    <description>Individual student attendance record for a session</description>
    <fields>
        <fullName>Class_Session__c</fullName>
        <description>Session for which attendance of student is tracked</description>
        <label>Class Session</label>
        <referenceTo>Class_SFDC_Session__c</referenceTo>
        <relationshipLabel>Class Session Attendances</relationshipLabel>
        <relationshipName>Class_Session_Attendances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Student_Name__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Name of the student for this attendance record</description>
        <inlineHelpText>Enter name of the student / contact</inlineHelpText>
        <label>Student Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>ClassroomStudent</value>
            </filterItems>
            <filterItems>
                <field>Contact.Active_Student__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Class Session Attendances</relationshipLabel>
        <relationshipName>Class_Session_Attendances</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Class Session Attendance</label>
    <nameField>
        <displayFormat>ATTEND-{00000}</displayFormat>
        <label>Class Session Attendance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Session Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SFDC_Enrollment__c.object
<CustomObject>
    <description>Connector object that associates a Student to a Class.</description>
    <fields>
        <fullName>Class__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Class</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SFDC_Class__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SFDC_Class__c</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>R00N40000001QAyfEAG</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Student Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>ClassroomStudent</value>
            </filterItems>
            <filterItems>
                <field>Contact.Active_Student__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Enrollments</relationshipLabel>
        <relationshipName>R00N40000001QAygEAG</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0000}</displayFormat>
        <label>Enrollment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CLASS_SFDC_EnrollmentTriggerHandler.cls
public with sharing class CLASS_SFDC_EnrollmentTriggerHandler extends TriggerHandler{

public override void afterInsert() {
    
    // Purpose is after the insert of a new Enrollment, look through all active sessions for the class of the enrollment
    //  and add the new student to the attendance list for the sessions so that instructors can mark the attendance
    //  of the new student.
    // List of new attendances to be inserted for new enrollment
    List<Class_SFDC_Session_Attendance__c> newAttendanceList = new List<Class_SFDC_Session_Attendance__c>();
    for(SFDC_Enrollment__c enroll : (List<SFDC_Enrollment__c>) Trigger.new) {
        // Get sessions for the class of this enrollment
        List<CLASS_SFDC_Session__c> sessions = [SELECT id, Class__c, Start_Date_Time__c
                                                FROM Class_SFDC_Session__c
                                                WHERE Class__c = :enroll.Class__c];
        
        for (CLASS_SFDC_Session__c aSession : sessions)  {
          // get the current attendance list. See if student is in active attendance lists
          // add student to attendance list if they are not in active attendance roster for sessions of the class
          List<Class_SFDC_Session_Attendance__c> attend = [SELECT id,Student_Name__c
                                                          FROM Class_SFDC_Session_Attendance__c
                                                          WHERE Class_Session__c = :aSession.id];
          Map<Id, Class_SFDC_Session_Attendance__c> attendanceMap = new Map<Id, Class_SFDC_Session_Attendance__c>();
          for (Class_SFDC_Session_Attendance__c attd : attend) {
            attendanceMap.put(attd.Student_Name__c, attd);
          }  
          if (!attendanceMap.containsKey(enroll.contact__c))    
              newAttendanceList.add(new Class_SFDC_Session_Attendance__c(student_Name__c=enroll.contact__c,
                                                                         Class_Session__c = aSession.id));
          
        } // end for session
       
    } // end for enrollments trigger.new
    insert newAttendanceList;
    
  } // end after insert

} // end class