objects/Class_SFDC_Session__c.object
<CustomObject>
    <description>A specific class session that is held with attendance documented</description>
    <fields>
        <fullName>Class__c</fullName>
        <description>Class for this session</description>
        <inlineHelpText>Enter the class for this session</inlineHelpText>
        <label>Class</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Class must be active and begin date is after today</errorMessage>
            <filterItems>
                <field>SFDC_Class__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <infoMessage>Class must be active and begin date is after today</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SFDC_Class__c</referenceTo>
        <relationshipName>Sessions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <defaultValue>Now()</defaultValue>
        <description>Date / Time the Class session starts</description>
        <inlineHelpText>Enter the Date and time the class session starts</inlineHelpText>
        <label>Start Date Time</label>
        <type>DateTime</type>
    </fields>
    <label>Class Session</label>
    <nameField>
        <displayFormat>SESSION-{00000}</displayFormat>
        <label>Class Session ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Class_SFDC_Session_Attendance__c.object
<CustomObject>
    <description>Individual student attendance record for a session</description>
    <fields>
        <fullName>Attended__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Mark student attendance</description>
        <inlineHelpText>Mark student attended</inlineHelpText>
        <label>Attended</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Class_Session__c</fullName>
        <description>Session for which attendance of student is tracked</description>
        <label>Class Session</label>
        <referenceTo>Class_SFDC_Session__c</referenceTo>
        <relationshipLabel>Class Session Attendances</relationshipLabel>
        <relationshipName>Class_Session_Attendances</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Class Session Attendance</label>
    <nameField>
        <displayFormat>ATTEND-{00000}</displayFormat>
        <label>Class Session Attendance ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Session Attendances</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/CLASS_SFDC_Settings__mdt.object
<CustomObject>
    <description>Holds all the application settings for the class attendance application</description>
    <fields>
        <fullName>Num_Days_Session_Retention__c</fullName>
        <defaultValue>7</defaultValue>
        <description>Number of days to keep session records that do not have any attendance marked</description>
        <inlineHelpText>How many days do you want to retain session records that have any attendance marked?</inlineHelpText>
        <label>Num Days Session Retention</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CLASS_SFDC_Setting</label>
    <pluralLabel>CLASS_SFDC_Settings</pluralLabel>
</CustomObject>

objects/SFDC_Class__c.object
<CustomObject>
    <description>Track the date and location of where your various Courses will be taught, and who has enrolled in this Class.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is the class active and open for enrollment or shown</description>
        <inlineHelpText>Is this class active and open for enrollment?</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Friday__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Meet Friday?</description>
        <inlineHelpText>Does the class meet Fridays?</inlineHelpText>
        <label>Friday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Monday__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Meeting Monday</description>
        <inlineHelpText>Does the class meet Monday?</inlineHelpText>
        <label>Monday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Saturday__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Meet Saturday?</description>
        <inlineHelpText>Does the class meet Saturday?</inlineHelpText>
        <label>Saturday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sunday__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Meet Sunday</description>
        <inlineHelpText>Does the class meet Sunday?</inlineHelpText>
        <label>Sunday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Thursday__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Meet Thursdays?</description>
        <inlineHelpText>Does the class meet Thursdays?</inlineHelpText>
        <label>Thursday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tuesday__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Meet Tuesday</description>
        <inlineHelpText>Does the class meet on Tuesdays?</inlineHelpText>
        <label>Tuesday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Wednesday__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Meet Wednesday?</description>
        <inlineHelpText>Does the class meet on Wednesday?</inlineHelpText>
        <label>Wednesday</label>
        <type>Checkbox</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CLASS_SFDC_DailyClassSessionCreator.cls
global class CLASS_SFDC_DailyClassSessionCreator implements Schedulable {
    
    global void execute(SchedulableContext SC) {
      List<SFDC_Class__c> activeClasses;
      List<Class_SFDC_Session__c> newSessions = new List<Class_SFDC_Session__c>();
      String strToday = System.now().format('EEE');
      //private final List<Class_SFDC_Session_Attendance__c> currAttendanceList;
      // create new class sessions for active classes
      activeClasses = [SELECT Id, Monday__c, Tuesday__c, Wednesday__c, Thursday__c, Friday__c, 
                              Saturday__c, Sunday__c FROM SFDC_Class__c
                                WHERE Active__c = true];
       //int currentDay = 0;
       for (SFDC_Class__c currclass : activeClasses) {
           // Check if class is scheduled for today before creating the session
           if (strToday.equalsIgnoreCase('Mon') && currclass.Monday__c) {
               Class_SFDC_Session__c aSession = new Class_SFDC_Session__c (Class__c = currclass.Id, Start_Date_Time__C = DateTime.now());
            	newSessions.add(aSession);
           }
           else if (strToday.equalsIgnoreCase('Tue') && currclass.Tuesday__c) {
               Class_SFDC_Session__c aSession = new Class_SFDC_Session__c (Class__c = currclass.Id, Start_Date_Time__C = DateTime.now());
            	newSessions.add(aSession);
           } 
           else if (strToday.equalsIgnoreCase('Wed') && currclass.Wednesday__c) {
               Class_SFDC_Session__c aSession = new Class_SFDC_Session__c (Class__c = currclass.Id, Start_Date_Time__C = DateTime.now());
            	newSessions.add(aSession);
           } 
           else if (strToday.equalsIgnoreCase('Thu') && currclass.Thursday__c) {
               Class_SFDC_Session__c aSession = new Class_SFDC_Session__c (Class__c = currclass.Id, Start_Date_Time__C = DateTime.now());
            	newSessions.add(aSession);
           } 
           else if (strToday.equalsIgnoreCase('Fri') && currclass.Friday__c) {
               Class_SFDC_Session__c aSession = new Class_SFDC_Session__c (Class__c = currclass.Id, Start_Date_Time__C = DateTime.now());
            	newSessions.add(aSession);
           } 
           else if (strToday.equalsIgnoreCase('Sat') && currclass.Saturday__c) {
               Class_SFDC_Session__c aSession = new Class_SFDC_Session__c (Class__c = currclass.Id, Start_Date_Time__C = DateTime.now());
            	newSessions.add(aSession);
           } 
           else if (strToday.equalsIgnoreCase('Sun') && currclass.Sunday__c) {
               Class_SFDC_Session__c aSession = new Class_SFDC_Session__c (Class__c = currclass.Id, Start_Date_Time__C = DateTime.now());
            	newSessions.add(aSession);
           } // end else if
            
          } // end for  
       insert newSessions;
      // For all Sessions older than Class_SFDC_SessionRetentionDays
      Decimal retentionDays = [SELECT id, DeveloperName,Num_Days_Session_Retention__c 
                               FROM CLASS_SFDC_Settings__mdt  
                               WHERE DeveloperName = 'Default_Settings' LIMIT 1].Num_Days_Session_Retention__c;
      retentionDays = retentionDays * -1; // negate to subtract days
      Date dateToDelete = date.today().addDays(retentionDays.intValue());
      // session later than retention date

      List<CLASS_SFDC_Session__c> sessions = [SELECT id, CreatedDate
                                                FROM Class_SFDC_Session__c
                                                WHERE CreatedDate < :dateToDelete];
      // go through attendance list for all these sessions and if they do not have any student attendance records
      // that are filled out; remove the session
      List<CLASS_SFDC_Session__c> sessionsToDelete = new List<CLASS_SFDC_Session__c>() ;
      for (CLASS_SFDC_Session__c aSession : sessions)  {
          Boolean noAttendance = true;
          List<Class_SFDC_Session_Attendance__c> attend = [SELECT id, Attended__c
                                                          FROM Class_SFDC_Session_Attendance__c
                                                          WHERE Class_Session__c = :aSession.id];
          for (Class_SFDC_Session_Attendance__c attd : attend) {
              if (attd.Attended__c) {noAttendance = false;}
          } 
          if (noAttendance) {sessionsToDelete.add(aSession);}
      }
      Delete sessionsToDelete;
      
   } // end execute
    
}