objects/SFDC_Class__c.object
<CustomObject>
    <description>Track the date and location of where your various Courses will be taught, and who has enrolled in this Class.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Is the class active and open for enrollment or shown</description>
        <inlineHelpText>Is this class active and open for enrollment?</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Friday__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Meet Friday?</description>
        <inlineHelpText>Does the class meet Fridays?</inlineHelpText>
        <label>Friday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Monday__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Meeting Monday</description>
        <inlineHelpText>Does the class meet Monday?</inlineHelpText>
        <label>Monday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Saturday__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Meet Saturday?</description>
        <inlineHelpText>Does the class meet Saturday?</inlineHelpText>
        <label>Saturday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sunday__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Meet Sunday</description>
        <inlineHelpText>Does the class meet Sunday?</inlineHelpText>
        <label>Sunday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Thursday__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Meet Thursdays?</description>
        <inlineHelpText>Does the class meet Thursdays?</inlineHelpText>
        <label>Thursday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tuesday__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Meet Tuesday</description>
        <inlineHelpText>Does the class meet on Tuesdays?</inlineHelpText>
        <label>Tuesday</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Wednesday__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Meet Wednesday?</description>
        <inlineHelpText>Does the class meet on Wednesday?</inlineHelpText>
        <label>Wednesday</label>
        <type>Checkbox</type>
    </fields>
    <label>Class</label>
    <nameField>
        <label>Class Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CLASS_SFDC_DailyClassSessionCreator_Test.cls
@isTest
public class CLASS_SFDC_DailyClassSessionCreator_Test {
    
    static final Integer maxClasses = 10;
    public static testMethod void testschedule() {
       
        List<SFDC_Class__c> classes = new List<SFDC_Class__c>();
        
        for (Integer i=0; i<maxClasses; i++) {
            SFDC_Class__c newClass = new SFDC_Class__c(Active__c=true, Monday__c=true, Tuesday__c=true,
                                                      Wednesday__c=true, Thursday__c=true, Friday__c=true,
                                                      Saturday__c=true, Sunday__c=true, Name='Class'+i);
            classes.add(newClass);
        }
        insert classes;

        Test.StartTest();
        CLASS_SFDC_DailyClassSessionCreator dailyBatch = new CLASS_SFDC_DailyClassSessionCreator();
		String sch = '0 0 23 * * ?'; 
        system.schedule('Test Daily Session Batch', sch, dailyBatch); 
        Test.stopTest(); }

}